version: "2"

linters:
  default: standard

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  default: standard
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
